### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by eodhun**
Changes have been made to D3D12 device creation and adapter search. In vulkan api implementation added callback function pointers to allocate memory for creating device and VMA.

### CODE REVIEW

**Comment by amerkoleci** [comment]
There are changes going in graphics system, probably won't merge those changes.

**Comment by eodhun** [comment]
How global are the changes in the graphics system?

**Comment by amerkoleci** [comment]
Very globally, basically I'm restoring D3D11 backend, then OpenGL then Vulkan, D3D12 will be last probably.
The rendering is simplified and will support single SwapChain with one command list under D3D11 and OpenGL.

**Comment by amerkoleci** [comment]
Vulkan has been just restored: https://github.com/amerkoleci/alimer/commit/b36d2750d5d017d77143093cdf818b5834fe3815

**Pull request closed without merging**
